######  Bag Of Words: Count Vectorizer
- Sparse Representation, that may consume too much memory & computing resources
- Doesn't capture meaning of words properly.

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [6]:
#On category column apply some transformation and generate new column
df['spam'] = df['Category'].apply(lambda x: 1 if x == 'spam' else 0)

In [7]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [8]:
df.shape

(5572, 3)

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam , test_size = 0.2) 

In [10]:
X_train.shape

(4457,)

In [11]:
X_test.shape

(1115,)

In [12]:
type(X_train)

pandas.core.series.Series

In [13]:
X_train[:4]

5209    I know you are thinkin malaria. But relax, chi...
4222    Plz note: if anyone calling from a mobile Co. ...
3597               Good morning princess! Happy New Year!
597                         Gud mrng dear have a nice day
Name: Message, dtype: object

In [14]:
type(y_train)

pandas.core.series.Series

In [15]:
y_train[:4]

5209    0
4222    0
3597    0
597     0
Name: spam, dtype: int64

In [16]:
#Bag of word model for numeric represntation
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv #gives sparse matrix of type numpy.int64

<4457x7776 sparse matrix of type '<class 'numpy.int64'>'
	with 59517 stored elements in Compressed Sparse Row format>

In [18]:
X_train_cv.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [19]:
X_train_cv.shape

(4457, 7776)

In [22]:
v.get_feature_names_out()[1000:1050]

array(['answering', 'answers', 'answr', 'antelope', 'antha', 'anthony',
       'anti', 'antibiotic', 'any', 'anybody', 'anyhow', 'anymore',
       'anyone', 'anyones', 'anyplaces', 'anythiing', 'anythin',
       'anything', 'anythingtomorrow', 'anytime', 'anyway', 'anyways',
       'anywhere', 'apart', 'apartment', 'apes', 'apnt', 'apo',
       'apologetic', 'apologise', 'apology', 'app', 'apparently',
       'appeal', 'appear', 'appendix', 'applebees', 'application',
       'apply', 'applyed', 'applying', 'appointment', 'appointments',
       'appreciate', 'appreciated', 'approaching', 'appropriate',
       'approve', 'approx', 'apps'], dtype=object)

In [24]:
v.get_feature_names_out().shape

(7776,)

In [25]:
dir(v)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_get_default_requests',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_validate_ngram_range',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',

In [26]:
# def get_spam_number(x):
#     if x == "spam":
#         return 1
#     return 0

In [28]:
v.vocabulary_

{'know': 3994,
 'you': 7736,
 'are': 1060,
 'thinkin': 6877,
 'malaria': 4362,
 'but': 1593,
 'relax': 5701,
 'children': 1807,
 'cant': 1661,
 'handle': 3338,
 'she': 6097,
 'would': 7637,
 'have': 3380,
 'been': 1306,
 'worse': 7630,
 'and': 973,
 'its': 3799,
 'gastroenteritis': 3105,
 'if': 3625,
 'takes': 6723,
 'enough': 2629,
 'to': 6964,
 'replace': 5735,
 'her': 3435,
 'loss': 4248,
 'temp': 6792,
 'will': 7547,
 'reduce': 5674,
 'give': 3166,
 'meds': 4449,
 'now': 4864,
 'just': 3909,
 'vomit': 7350,
 'self': 6019,
 'limiting': 4159,
 'illness': 3640,
 'has': 3367,
 'which': 7516,
 'means': 4439,
 'in': 3668,
 'few': 2844,
 'days': 2214,
 'it': 3791,
 'completely': 1961,
 'stop': 6525,
 'plz': 5286,
 'note': 4851,
 'anyone': 1012,
 'calling': 1637,
 'from': 3039,
 'mobile': 4566,
 'co': 1894,
 'amp': 961,
 'asks': 1111,
 'type': 7140,
 'lt': 4286,
 'gt': 3285,
 'or': 4994,
 'do': 2398,
 'not': 4850,
 'so': 6308,
 'disconnect': 2369,
 'the': 6844,
 'call': 1624,
 'coz': 2075,

In [40]:
v.get_feature_names_out()[1771]

'chatlines'

In [41]:
X_train_np =X_train_cv.toarray()
#Gives 1st email
X_train_np[:4][0]

array([0, 0, 0, ..., 0, 0, 0])

In [42]:
# In the 1st email, what are tghe indexes which are non-zero
np.where(X_train_np[0]!=0)

(array([ 973, 1060, 1306, 1593, 1661, 1807, 1961, 2214, 2629, 2844, 3105,
        3166, 3338, 3367, 3380, 3435, 3625, 3640, 3668, 3791, 3799, 3909,
        3994, 4159, 4248, 4362, 4439, 4449, 4864, 5674, 5701, 5735, 6019,
        6097, 6525, 6723, 6792, 6877, 6964, 7350, 7516, 7547, 7630, 7637,
        7736]),)

In [43]:
X_train[:4]

5209    I know you are thinkin malaria. But relax, chi...
4222    Plz note: if anyone calling from a mobile Co. ...
3597               Good morning princess! Happy New Year!
597                         Gud mrng dear have a nice day
Name: Message, dtype: object

In [44]:
#1st sample
X_train[:4][5209]

'I know you are thinkin malaria. But relax, children cant handle malaria. She would have been worse and its gastroenteritis. If she takes enough to replace her loss her temp will reduce. And if you give her malaria meds now she will just vomit. Its a self limiting illness she has which means in a few days it will completely stop'

In [45]:
#Vector form
X_train_np[0][1771]

0

In [48]:
#Building an ML Model
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [50]:
X_test_cv = v.transform(X_test)

In [51]:
from sklearn.metrics import classification_report
y_pred = model.predict(X_test_cv)
classification_report(y_test,y_pred)

'              precision    recall  f1-score   support\n\n           0       0.98      0.99      0.99       968\n           1       0.96      0.90      0.93       147\n\n    accuracy                           0.98      1115\n   macro avg       0.97      0.95      0.96      1115\nweighted avg       0.98      0.98      0.98      1115\n'

In [55]:
emails = [
    'Hey mohan, can we get together to watch football game tomorrow?',
    "Upto 20% discount on parking, exclusive offer just for you. Don't miss this reward!"
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

In [56]:
#Alternative Method
#Pipeline is the convenient API
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer',CountVectorizer()),
    ('nb',MultinomialNB())
])

In [58]:
clf.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [59]:
y_pred = clf.predict(X_test)
classification_report(y_test,y_pred)

'              precision    recall  f1-score   support\n\n           0       0.98      0.99      0.99       968\n           1       0.96      0.90      0.93       147\n\n    accuracy                           0.98      1115\n   macro avg       0.97      0.95      0.96      1115\nweighted avg       0.98      0.98      0.98      1115\n'